name: ${project.name}
version: ${project.version}
main: ${main.class}
author: ${author}

api-version: '1.20'

softdepend: [PlaceholderAPI]

commands:
  hubpro:
    description: HubPro main command
    usage: /<command> reloadconfig
    aliases: [hp]
    permission: hubpro.command.reload